# Generated by Django 3.2.20 on 2023-08-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230801_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocket',
            name='height',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
