# Generated by Django 3.2.20 on 2023-08-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rocket_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocket',
            name='diameter',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rocket',
            name='mass',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
