# Generated by Django 3.2.20 on 2023-08-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230801_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocket',
            name='diameter',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='height',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='mass',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
