# Generated by Django 3.2.20 on 2023-08-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230801_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocket',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
