# Generated by Django 3.2.20 on 2023-08-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_rocket_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocket',
            name='height',
            field=models.IntegerField(),
        ),
    ]
