# Generated by Django 3.2.20 on 2023-08-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_rocket_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocket',
            name='diameter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='mass',
            field=models.IntegerField(),
        ),
    ]
