# Generated by Django 3.2.20 on 2023-08-02 02:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230801_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocket',
            name='diameter',
            field=models.IntegerField(validators=[api.models.validate_metrics]),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='height',
            field=models.IntegerField(validators=[api.models.validate_metrics]),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='mass',
            field=models.IntegerField(validators=[api.models.validate_metrics]),
        ),
    ]
