# Generated by Django 3.2.20 on 2023-08-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230801_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocket',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
