# Generated by Django 3.2.20 on 2023-08-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rocket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocket',
            name='image',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/'),
        ),
    ]
